// <auto-generated />
using System;
using Copiloto.Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Copiloto.Api.Persistencia.Migrations
{
    [DbContext(typeof(CopilotoDbContext))]
    [Migration("20260915194627_DossiePersistido")]
    partial class DossiePersistido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Copiloto.Dominio.Conversas.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("conversas", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Conversas.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ConversaId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("DuracaoDaMidia")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("EnviadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDeMidia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.HasIndex("EnviadaEm")
                        .HasDatabaseName("ix_mensagens_enviada_em");

                    b.ToTable("mensagens", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Dossies.Dossie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid");

                    b.Property<string>("DirecaoLida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Lacunas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TemperaturaLida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DealId", "GeradoEm")
                        .HasDatabaseName("ix_dossies_deal_gerado");

                    b.ToTable("dossies", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Fichas.FichaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("_historico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("historico");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique()
                        .HasDatabaseName("ux_fichas_lead");

                    b.ToTable("fichas_cliente", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Ia.AiInvocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CustoEmReais")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("DealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("Quando")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DealId")
                        .HasDatabaseName("ix_ai_invocations_deal");

                    b.ToTable("ai_invocations", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Vendas.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AbertoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustoIaAcumulado")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Estagio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("FechadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Vendas.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasDatabaseName("ux_leads_telefone");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Conversas.Mensagem", b =>
                {
                    b.HasOne("Copiloto.Dominio.Conversas.Conversa", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Copiloto.Dominio.Dossies.Dossie", b =>
                {
                    b.OwnsMany("Copiloto.Dominio.Dossies.Sinal", "Sinais", b1 =>
                        {
                            b1.Property<Guid>("DossieId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("MensagemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TrechoCitado")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DossieId", "__synthesizedOrdinal");

                            b1.ToTable("dossies");

                            b1
                                .ToJson("sinais")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DossieId");
                        });

                    b.Navigation("Sinais");
                });

            modelBuilder.Entity("Copiloto.Dominio.Fichas.FichaCliente", b =>
                {
                    b.OwnsOne("Copiloto.Dominio.Fichas.SobreAEmpresa", "Empresa", b1 =>
                        {
                            b1.Property<Guid>("FichaClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ComoChegou")
                                .HasColumnType("text");

                            b1.Property<string>("Momento")
                                .HasColumnType("text");

                            b1.Property<string>("Porte")
                                .HasColumnType("text");

                            b1.Property<string>("Ramo")
                                .HasColumnType("text");

                            b1.HasKey("FichaClienteId");

                            b1.ToTable("fichas_cliente");

                            b1.WithOwner()
                                .HasForeignKey("FichaClienteId");
                        });

                    b.OwnsOne("Copiloto.Dominio.Fichas.SobreAPessoa", "Pessoa", b1 =>
                        {
                            b1.Property<Guid>("FichaClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Cargo")
                                .HasColumnType("text");

                            b1.Property<string>("EstiloObservado")
                                .HasColumnType("text");

                            b1.Property<string>("PapelNaDecisao")
                                .HasColumnType("text");

                            b1.Property<string>("QuemMaisDecide")
                                .HasColumnType("text");

                            b1.HasKey("FichaClienteId");

                            b1.ToTable("fichas_cliente");

                            b1.WithOwner()
                                .HasForeignKey("FichaClienteId");
                        });

                    b.OwnsOne("Copiloto.Dominio.Fichas.SobreONegocio", "Negocio", b1 =>
                        {
                            b1.Property<Guid>("FichaClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("OrcamentoEstimado")
                                .HasColumnType("text");

                            b1.Property<string>("ProvavelNecessidade")
                                .HasColumnType("text");

                            b1.Property<string>("RiscoConhecido")
                                .HasColumnType("text");

                            b1.Property<string>("UsaHoje")
                                .HasColumnType("text");

                            b1.HasKey("FichaClienteId");

                            b1.ToTable("fichas_cliente");

                            b1.WithOwner()
                                .HasForeignKey("FichaClienteId");
                        });

                    b.Navigation("Empresa")
                        .IsRequired();

                    b.Navigation("Negocio")
                        .IsRequired();

                    b.Navigation("Pessoa")
                        .IsRequired();
                });

            modelBuilder.Entity("Copiloto.Dominio.Ia.AiInvocation", b =>
                {
                    b.HasOne("Copiloto.Dominio.Vendas.Deal", null)
                        .WithMany("Invocacoes")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Copiloto.Dominio.Conversas.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Copiloto.Dominio.Vendas.Deal", b =>
                {
                    b.Navigation("Invocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
