// <auto-generated />
using System;
using Copiloto.Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Copiloto.Api.Persistencia.Migrations
{
    [DbContext(typeof(CopilotoDbContext))]
    [Migration("20260916160605_PrecedentesComPgvector")]
    partial class PrecedentesComPgvector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Copiloto.Dominio.Auditoria.AcessoRegistrado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Quando")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeadId", "Quando")
                        .HasDatabaseName("ix_acessos_lead");

                    b.HasIndex("UsuarioId", "Quando")
                        .HasDatabaseName("ix_acessos_usuario");

                    b.ToTable("acessos", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Conversas.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("conversas", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Conversas.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ConversaId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("DuracaoDaMidia")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("EnviadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDeMidia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.HasIndex("EnviadaEm")
                        .HasDatabaseName("ix_mensagens_enviada_em");

                    b.ToTable("mensagens", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Dossies.Dossie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid");

                    b.Property<string>("DirecaoLida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Lacunas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TemperaturaLida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DealId", "GeradoEm")
                        .HasDatabaseName("ix_dossies_deal_gerado");

                    b.ToTable("dossies", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Fichas.FichaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Negocio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("negocio");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pessoa");

                    b.Property<string>("_historico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("historico");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique()
                        .HasDatabaseName("ux_fichas_lead");

                    b.ToTable("fichas_cliente", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Ia.AiInvocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CustoEmReais")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("DealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("Quando")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DealId")
                        .HasDatabaseName("ix_ai_invocations_deal");

                    b.ToTable("ai_invocations", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Rag.Precedente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Trecho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Vetor")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_precedentes_lead");

                    b.HasIndex("Vetor")
                        .HasDatabaseName("ix_precedentes_vetor");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Vetor"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Vetor"), new[] { "vector_cosine_ops" });

                    b.ToTable("precedentes", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Vendas.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AbertoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustoIaAcumulado")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Estagio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("EstagioDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FechadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Vendas.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AnaliseDeIaSuspensa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("OpostoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Relacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasDatabaseName("ux_leads_telefone");

                    b.HasIndex("VendedorId")
                        .HasDatabaseName("ix_leads_vendedor");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Vendas.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Copiloto.Dominio.Conversas.Mensagem", b =>
                {
                    b.HasOne("Copiloto.Dominio.Conversas.Conversa", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Copiloto.Dominio.Dossies.Dossie", b =>
                {
                    b.OwnsMany("Copiloto.Dominio.Dossies.Objecao", "Objecoes", b1 =>
                        {
                            b1.Property<Guid>("DossieId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("MensagemId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("PorComportamento")
                                .HasColumnType("boolean");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TrechoCitado")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DossieId", "__synthesizedOrdinal");

                            b1.ToTable("dossies");

                            b1
                                .ToJson("objecoes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DossieId");
                        });

                    b.OwnsMany("Copiloto.Dominio.Dossies.Sinal", "Sinais", b1 =>
                        {
                            b1.Property<Guid>("DossieId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("MensagemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TrechoCitado")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DossieId", "__synthesizedOrdinal");

                            b1.ToTable("dossies");

                            b1
                                .ToJson("sinais")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DossieId");
                        });

                    b.Navigation("Objecoes");

                    b.Navigation("Sinais");
                });

            modelBuilder.Entity("Copiloto.Dominio.Ia.AiInvocation", b =>
                {
                    b.HasOne("Copiloto.Dominio.Vendas.Deal", null)
                        .WithMany("Invocacoes")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Copiloto.Dominio.Conversas.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Copiloto.Dominio.Vendas.Deal", b =>
                {
                    b.Navigation("Invocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
